#!/bin/sh

case "$1" in
    start)
        echo "starting aesdsocket"
        start-stop-daemon -n aesdsocket -a /usr/bin/aesdsocket -S -- -d
        ;;
    stop)
        start-stop-daemon -n aesdsocket -K
        ;;
    *)
        echo "Usage $0 {start|stop}"
        exit 1
esac
